using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Drawing.Imaging;
using System.Globalization;
using System.IO;

namespace AiPets
{
    /// <summary>Sprite atlas generated by pets\&lt;id&gt;\art\make_sprites.py (sprites\atlas.png + atlas.txt).</summary>
    sealed class Atlas : IDisposable
    {
        public int CellW { get; private set; }
        public int CellH { get; private set; }

        /// <summary>The unmirrored frames look to the left (atlas line "facing left").</summary>
        public bool FacingLeft { get; private set; }

        /// <summary>Idle phases of the normal face (frames normal_0 … normal_N).</summary>
        public int Phases { get; private set; }

        /// <summary>Rows the character covers in the idle frame normal_0: her height in sprite pixels.</summary>
        public int FigureHeight { get; private set; }

        readonly Bitmap sheet;
        readonly Dictionary<string, Point> frames = new Dictionary<string, Point>();
        readonly Dictionary<string, Rectangle> sprites = new Dictionary<string, Rectangle>();
        readonly Dictionary<string, Point> pivots = new Dictionary<string, Point>();
        readonly Dictionary<string, Point> anchors = new Dictionary<string, Point>();
        readonly Dictionary<string, string[]> anims = new Dictionary<string, string[]>();
        readonly ImageAttributes clampEdges = new ImageAttributes();
        readonly bool[] hoverMask, hoverMaskMirrored;

        public static Atlas Load(string dir)
        {
            // decode from memory: new Bitmap(path) would keep atlas.png locked while the pet runs
            using (var png = new MemoryStream(File.ReadAllBytes(Path.Combine(dir, "atlas.png"))))
            using (var decoded = new Bitmap(png))
                return new Atlas(decoded, File.ReadAllText(Path.Combine(dir, "atlas.txt")));
        }

        Atlas(Bitmap decoded, string manifest)
        {
            sheet = new Bitmap(decoded.Width, decoded.Height, PixelFormat.Format32bppPArgb);
            using (var g = Graphics.FromImage(sheet))
            {
                g.CompositingMode = CompositingMode.SourceCopy;
                g.DrawImage(decoded, new Rectangle(0, 0, decoded.Width, decoded.Height),
                    0, 0, decoded.Width, decoded.Height, GraphicsUnit.Pixel);
            }
            // nearest-neighbour sampling must never bleed in from the neighbouring atlas cell
            clampEdges.SetWrapMode(WrapMode.TileFlipXY);

            foreach (string raw in manifest.Split('\n'))
            {
                string[] p = raw.Trim().Split(' ');
                switch (p[0])
                {
                    case "cell":
                        CellW = Int(p[1]);
                        CellH = Int(p[2]);
                        break;
                    case "frame":
                        frames[p[1]] = new Point(Int(p[2]), Int(p[3]));
                        break;
                    case "sprite":
                        sprites[p[1]] = new Rectangle(Int(p[2]), Int(p[3]), Int(p[4]), Int(p[5]));
                        pivots[p[1]] = new Point(Int(p[6]), Int(p[7]));
                        break;
                    case "anchor":
                        anchors[p[1]] = new Point(Int(p[2]), Int(p[3]));
                        break;
                    case "facing":
                        FacingLeft = p[1] == "left";
                        break;
                    case "anim":
                        var names = new string[p.Length - 2];
                        Array.Copy(p, 2, names, 0, names.Length);
                        anims[p[1]] = names;
                        break;
                }
            }
            int phases = 0;
            while (frames.ContainsKey("normal_" + phases))
                phases++;
            Phases = Math.Max(1, phases);
            bool[] idle = Solid(frames["normal_0"]);
            FigureHeight = VisibleRows(idle);
            hoverMask = BuildMask(idle, 2);
            hoverMaskMirrored = BuildMask(Solid(frames["m_normal_0"]), 2);
        }

        static int Int(string s)
        {
            return int.Parse(s, CultureInfo.InvariantCulture);
        }

        public bool HasFrame(string name)
        {
            return frames.ContainsKey(name);
        }

        public bool HasSprite(string name)
        {
            return sprites.ContainsKey(name);
        }

        /// <summary>Sprite names of an "anim" line, or the fallback if the atlas has none.</summary>
        public string[] Anim(string name, string[] fallback)
        {
            string[] names;
            return anims.TryGetValue(name, out names) ? names : fallback;
        }

        /// <summary>All anims whose name starts with prefix (twinkle, twinkle2 …).</summary>
        public List<string[]> AnimsWithPrefix(string prefix)
        {
            var list = new List<string[]>();
            foreach (KeyValuePair<string, string[]> kv in anims)
                if (kv.Key.StartsWith(prefix, StringComparison.Ordinal))
                    list.Add(kv.Value);
            return list;
        }

        /// <summary>Anchor in cell coordinates, flipped for the mirrored frames.</summary>
        public Point Anchor(string name, bool mirrored)
        {
            Point a = anchors[name];
            return mirrored ? new Point(CellW - 1 - a.X, a.Y) : a;
        }

        public Size SpriteSize(string name)
        {
            return sprites[name].Size;
        }

        /// <summary>Draws a frame stretched onto dest (nearest neighbour, also for fractional zoom).</summary>
        public void DrawFrame(Graphics g, string name, Rectangle dest)
        {
            Point src = frames[name];
            g.DrawImage(sheet, dest, src.X, src.Y, CellW, CellH, GraphicsUnit.Pixel, clampEdges);
        }

        /// <summary>Draws a sprite so that its pivot pixel lands on (x, y), zoom screen pixels per sprite pixel.</summary>
        public void DrawSprite(Graphics g, string name, int x, int y, double zoom)
        {
            Rectangle src = sprites[name];
            Point pivot = pivots[name];
            var dest = new Rectangle(x - Round(pivot.X * zoom), y - Round(pivot.Y * zoom), Round(src.Width * zoom), Round(src.Height * zoom));
            g.DrawImage(sheet, dest, src.X, src.Y, src.Width, src.Height, GraphicsUnit.Pixel, clampEdges);
        }

        static int Round(double value)
        {
            return (int)Math.Round(value);
        }

        /// <summary>True if the cell pixel belongs to the character (slightly dilated so gaps don't flicker).</summary>
        public bool HitCharacter(int cx, int cy, bool mirrored)
        {
            if (cx < 0 || cy < 0 || cx >= CellW || cy >= CellH)
                return false;
            return (mirrored ? hoverMaskMirrored : hoverMask)[cy * CellW + cx];
        }

        /// <summary>Which pixels of a frame are not transparent, row by row.</summary>
        bool[] Solid(Point cell)
        {
            var solid = new bool[CellW * CellH];
            for (int y = 0; y < CellH; y++)
                for (int x = 0; x < CellW; x++)
                    solid[y * CellW + x] = sheet.GetPixel(cell.X + x, cell.Y + y).A > 0;
            return solid;
        }

        /// <summary>Rows from the topmost to the lowest visible pixel (the whole cell if the frame is empty).</summary>
        int VisibleRows(bool[] solid)
        {
            int top = -1, bottom = -1;
            for (int i = 0; i < solid.Length; i++)
            {
                if (!solid[i])
                    continue;
                if (top < 0)
                    top = i / CellW;
                bottom = i / CellW;
            }
            return top < 0 ? CellH : bottom - top + 1;
        }

        bool[] BuildMask(bool[] solid, int grow)
        {
            var mask = new bool[CellW * CellH];
            for (int y = 0; y < CellH; y++)
                for (int x = 0; x < CellW; x++)
                {
                    for (int dy = -grow; dy <= grow && !mask[y * CellW + x]; dy++)
                        for (int dx = -grow; dx <= grow; dx++)
                        {
                            int nx = x + dx, ny = y + dy;
                            if (nx >= 0 && ny >= 0 && nx < CellW && ny < CellH && solid[ny * CellW + nx])
                            {
                                mask[y * CellW + x] = true;
                                break;
                            }
                        }
                }
            return mask;
        }

        public void Dispose()
        {
            sheet.Dispose();
            clampEdges.Dispose();
        }
    }
}
